const http = require('http')

const server = http.createServer((req, res) => {
  console.log(req.url, req.method, req.headers)
  // process.exit()
  res.setHeader('Content-Type', 'text/html')
  res.write('<html>')
  res.write('<head>')
  res.write('<title>My Frist Page')
  res.write('</title>')
  res.write('</head>')
  res.write('<body>')
  res.write('<h1>Hello from my NodeJS Server!')
  res.write('</h1>')
  res.write('</body>')
  res.write('</html>')
  res.end()
})

server.listen(3000)